#!/bin/bash

DOCKER_REPO="${GITHUB_REPOSITORY##*/}"
branch="${GITHUB_REF_NAME#ft/}"

echo "DOCKER_REPO=$DOCKER_REPO" >>$GITHUB_ENV
echo "DOCKER_USERNAME=$DOCKER_USERNAME" >>$GITHUB_ENV
echo "DOCKER_PASSWORD=$DOCKER_PASSWORD" >>$GITHUB_ENV
echo "DOCKER_IMAGE=$DOCKER_USERNAME/$DOCKER_REPO" >>$GITHUB_ENV
echo "DOCKER_TAG=$DOCKER_USERNAME/$DOCKER_REPO:$branch" >>$GITHUB_ENV
