name: Build & Push Docker Image

on:
  workflow_call:
    outputs:
      image_tag:
        description: "Full image tag pushed"
        value: ${{ jobs.docker.outputs.image_tag }}
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.output.outputs.image_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          touch .env
          echo "${{secrets.ENV}}" >> .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare Docker Context
        run: ./scripts/prepare-docker-context.sh
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{env.DOCKER_USERNAME}}
          password: ${{env.DOCKER_PASSWORD}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{env.DOCKER_TAG}}

      - name: Output
        id: output
        run: echo "image_tag=$DOCKER_TAG" >>$GITHUB_OUTPUT

