name: E2E Tests with Cypress

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    env:
      GOOGLE_USERNAME: ${{ secrets.GOOGLE_USERNAME }}
      GOOGLE_PASSWORD: ${{ secrets.GOOGLE_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Start Next.js app
        run: npm run start &
        env:
          NODE_ENV: production

      - name: Wait for app to be ready
        uses: jakejarvis/wait-action@v0.1.0
        with:
          url: 'http://localhost:3000'
          timeout: 60

      - name: Run Cypress tests
        run: npx cypress run
