name: Test E2E

on:
  workflow_call:
    inputs:
      docker_image:
        required: true
        type: string
      cypress_tags:
        required: true
        type: string

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Debug
        run: echo ${{ inputs.cypress_tags }}

      - name: Run test
        run: docker run -e "CYPRESS_grepTags=${{inputs.cypress_tags}}" ${{inputs.docker_image}} ci 
